## 3. 넘파이
넘파이란? 다차원배열과 수학 함수를 제공하는 모듈(라이브러리)  
모듈이란? 필요한 기능을 미리 만들어두고 가져다 쓰는 것

3.1 ndarray
다차원 배열  
다차원 배열의 특징:  
1.리스트와 비교했을때 계산 속도가 빠름  
2.리스트와 달리 모든 요소의 타입이 같음

In [8]:
# 먼저 numpy 모듈 가져오기
# 외부에 있는 모듈 파일을 가지고 올때는 import
# 모듈의 이름이 길때는 별칭 붙이기 as np
import numpy as np

In [10]:
# 넘파이 배열 만들기
# 입력값: 리스트
# 결과: 넘파이 배열
a = np.array([1,2,3])
a
b = np.array(['a', 'b', 'c'])
b

array(['a', 'b', 'c'], dtype='<U1')

2차원 배열  


In [13]:
# 2차원 배열 생성
# 2차원 배열은 1차원 배열의 묶음
c = np.array([[1,2,3], [4,5,6]])
c
# 3행 3열 크기의 2차원 배열 생성
d = np.array([[1,2,3], [4,5,6], [7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# arrange : 숫자 여러개를 생성하는 함수
# 연속된 숫자를 10개 생성
a = np.arange(10)
# 1부터 10까지 생성
b = np.arange(1,11)
# 1부터 10까지 2씩 건너뛰면서 생성
c = np.arange(1,11,2)
c

array([1, 3, 5, 7, 9])

In [45]:
# 연습문제
scores = np.array([85,90,78,92,88])
heights = np.array([160,165,170,175,180])
prices = np.array([1200,1500,1800,2100])
temps = np.array([20,22,19,25,30])
print(scores)
print(heights)
print(prices)
print(temps)

[85 90 78 92 88]
[160 165 170 175 180]
[1200 1500 1800 2100]
[20 22 19 25 30]


In [47]:
# 연습문제
a = np.arange(5)
b = np.arange(10)
c = np.arange(3, 8)
d = np.arange(-2, 3)
print(a)
print(b)
print(c)
print(d)

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]
[-2 -1  0  1  2]


In [43]:
# zeros : 배열을 생성하고 값을 0으로 초기화
np.zeros(10)
# 2차원 배열 생성
np.zeros((3,3)) # 행 열

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
# 3개 크기의 1차원 배열 생성
# 파이썬의 리스트와 달리 넘파이 배열은 모든 원소의 자료형이 같다.
a = np.array([1,2,3])
print(a.dtype) # 자료형
print(a.ndim) # 배열의 차원
print(a.shape) #행열 크기

int64
1
(3,)


In [49]:
# 2행 3열의 2차원 배열 생성
b = np.array([[1,2,3], [4,5,6]])
print(b.dtype)
print(b.ndim)
print(b.shape)

int64
2
(2, 3)


In [53]:
# 실수형 1차원 배열 생성
arr = np.array([1.1,2.1,3.1])
# 자료형 확인
arr.dtype
# 배열의 형변환
# float -> int
arr2 = arr.astype(np.int32)
arr2
arr2.dtype

dtype('int32')

In [54]:
lis = [1,2,3]
# 파이썬 각 원소에 3씩 더하기
# 리스트의 원소에 하나씩 계산하려면 for 반복문을 사용해야한다.
for i in lis:
    print(i+3)

4
5
6


In [56]:
# 넘파이 배열 생성
# 넘파이 배열은 for문 없이 각 원소에 값을 계산할 수 있다.
# 넘파이 배열을 자동으로 각 원소에 반복 수행이 된다.
a = np.array([1,2,3])
# 각 원소에 3씩 더하기
a + 3

array([4, 5, 6])

In [58]:
a  = np.array([1,2,3])
b = np.array([4,5,6])

# 배열 두개를 비고
a > b

array([False, False, False])

인덱스와 슬라이스

In [64]:
# 1차원 배열 생성
# 0~9 숫자 만들고 1차원 배열 생성
a = np.arange(10)
print(a)
# 배열의 원소 하나 꺼내기
a[1]
# 범위로 값 꺼내기 (슬라이스)
a[3:6]
# 원소 값 변경하기
# 두번째 원소의 값 변경하기
a[1] = 99
a
# 특정 범위에 있는 값을 모두 변경하기
# 3,4,5 번째 데이터 변경
a[3:6] = 88
a

[0 1 2 3 4 5 6 7 8 9]


array([ 0, 99,  2, 88, 88, 88,  6,  7,  8,  9])

In [66]:
# 배열 전체 선택
# a를 출력하는 것과 같다.
a[:]

array([ 0, 99,  2, 88, 88, 88,  6,  7,  8,  9])

In [67]:
# 슬라이스로 배열 전체를 선택하고, 값 변경
a[:] = 999
a

array([999, 999, 999, 999, 999, 999, 999, 999, 999, 999])

In [68]:
# 연습문제
arr = np.array([10,20,30,40,50])

In [72]:
# 연습문제
print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


In [73]:
arr[1] = 200
arr

array([ 10, 200,  30,  40,  50])

In [74]:
arr[3] = 999
arr

array([ 10, 200,  30, 999,  50])

In [75]:
# 연습문제
arr = np.array(['가','나','다','라','마'])

In [79]:
# 연습문제
print(arr[1])
print(arr[3])
print(arr[-1])
arr[0] = '하'
print(arr)
arr[2] = '호'
print(arr)

나
라
마
['하' '나' '호' '라' '마']
['하' '나' '호' '라' '마']


In [187]:
# 연습문제
arr = np.array([10,20,30,40,50,60,70])

In [85]:
print(arr[:3])
print(arr[3:])
print(arr[1:5])

[10 20 30]
[40 50 60 70]
[20 30 40 50]


In [86]:
# 연습문제
arr = np.array(['a','b','c','d','e','f','g'])

In [87]:
print(arr[:3])
print(arr[3:])
print(arr[1:5])

['a' 'b' 'c']
['d' 'e' 'f' 'g']
['b' 'c' 'd' 'e']


2차원 배열의 인덱싱

In [88]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [92]:
# 2차원 배열의 인덱스
# 행(인덱스)
# 열(컬럼)
# 첫번째 행 꺼내기
arr[0]

array([1, 2, 3])

In [101]:
# 1 꺼내기
arr[0][0]
# 9 꺼내기
arr[2][2]
# 5 꺼내기
arr[1][1]
arr[1,1]

np.int64(5)

In [103]:
# 배열 원소의 값 바꾸기
# 0 -> 1
arr[0,0] = 0
arr
# 5 -> 0
arr[1,1] = 0
arr

array([[0, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

2차원 배열 슬라이스

In [105]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
# 행: 1번 2번
# 열: 1번 2번
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [113]:
# 행: 0번 1번
# 열: 0번 1번
arr[ :2, :2]

array([[1, 2],
       [4, 5]])

In [114]:
# 행: 1번 행만 선택
# 열: 0 1 번 
arr[1,0:2]

array([4, 5])

In [186]:
# 연습문제
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [126]:
# 연습문제
print(arr[0, 1])
print(arr[2, 0])
print(arr[1])
print(arr[ : , 1])
arr[0, 2] = 300
print(arr)

20
70
[40 50 60]
[20 50 80]
[[ 10  20 300]
 [ 40  50  60]
 [ 70  80  90]]


In [185]:
# 연습문제
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [132]:
print(arr[1, 2])
print(arr[3, 0])
print(arr[2])
print(arr[ : , 3])
arr[0, 3] = 100
arr

7
13
[ 9 10 11 12]
[ 4  8 12 16]


array([[  1,   2,   3, 100],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [133]:
# 연습문제
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [138]:
# 연습문제
print(arr[0, :2])
print(arr[1:3])
print(arr[ : , 1:3])

[10 20]
[[40 50 60]
 [70 80 90]]
[[20 30]
 [50 60]
 [80 90]]


불리언 인덱스  
인덱스란? 데이터의 위치

In [140]:
# 학생 배열 생성
students = np.array(['철수','영희','민수','철수','철수'])
# 학생들의 대출 이력
books = np.array([['수학의 정석', 7],['해리포터', 10],['파이썬 입문', 5], ['한국사', 5], ['데미안', 12]])

In [146]:
# 위에서 철수의 대출 이력만 조회하기
# 배열 == '비교값'
# 배열 전체에 철수를 비교
# 총 5번 비교하고 bool배열 반환
students == '철수'
arr = (students == '철수')
arr

array([ True, False, False,  True,  True])

In [148]:
# books 배열의 인덱스에 bool 배열 넣기
# true 에 해당하는 원소만 반환
# 조건에 맞는 원소를 꺼낼때 사용
books[students == '철수']

array([['수학의 정석', '7'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

In [150]:
print(students != '철수')
# 철수가 아닌 대출 이력 찾기
books[students != '철수']

[False  True  True False False]


array([['해리포터', '10'],
       ['파이썬 입문', '5']], dtype='<U21')

In [155]:
# '수학의 정석'을 찾아서 제목을 books == '수학의 정석'으로 바꾸기
books == '수학의 정석'
# bool 배열로 원소를 찾고 값 교체
books[books == '수학의 정석'] = '자바의 정석'

In [157]:
# 대출 이력 중에서 철수가 아닌 항목을 찾고
# 행 전체를 7로 바꾸기
students != '철수'
books[students != '철수'] = 7
books

array([['자바의 정석', '7'],
       ['7', '7'],
       ['7', '7'],
       ['한국사', '5'],
       ['데미안', '12']], dtype='<U21')

In [182]:
# 연습문제
arr = np.array([10,20,30,40,50,60,70])


In [184]:
# 연습문제
result = arr[arr > 30]
print(result)
result = arr[arr%2 == 0]
print(result)
arr[arr > 50] = 999
arr

[40 50 60 70]
[10 20 30 40 50 60 70]


array([ 10,  20,  30,  40,  50, 999, 999])

In [189]:
# 연습문제
employees = np.array(['짱구','철수','유리','맹구','훈이'])
salaries = np.array([250,320,280,400,150])

In [198]:
# 연습문제
print(salaries[employees == '맹구'])
print(employees[salaries >= 300])
salaries[salaries < 200] = 200
salaries

[400]
['철수' '맹구']


array([250, 320, 280, 400, 200])

3.2 배열의 모양 바꾸기

In [200]:
# 1~9 숫자가 담긴 1차원 배열 생성
# reshape: 배열의 형태를 바꾸는 함수
# 1차원 -> 2차원
# 3행 3열 크기의 배열로 변환
print(np.arange(1,10))
arr = np.arange(1,10).reshape(3,3)
arr

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [201]:
# 1~16 숫자가 담긴 1차원 배열
# 1차원 -> 2차원
print(np.arange(1,17))
a = np.arange(1,17).reshape(4,4)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [202]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [203]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [214]:
a = np.arange(0,12).reshape(3,4)
print(a)
a = np.arange(1,17).reshape(4,4)
print(a)
a = np.arange(1,21).reshape(5,4)
print(a)
a = np.arange(10,26).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


3.3 난수를 생성하는 방법  
난수란 랜덤값을 의미한다.

In [215]:
# 랜덤값 만들기
# 표준 정규 분포: 표준 편차가 1인 그래프에서 랜덤값을 생성 (-3 ~ 3)
# 랜덤겂 10개 생성
arr = np.random.standard_normal(size = 10)
arr

array([ 0.11469214,  1.10852002, -0.55573135,  1.98322848, -1.37890506,
        0.71049901,  0.40074496, -1.66607417, -1.03997382, -1.16547317])

In [216]:
# 균일 분포: 범위 0 ~ 1. 모든 값이 같은 확률로 나옴
arr = np.random.uniform(size = 10)
arr

array([0.67980901, 0.4869948 , 0.63518836, 0.11248018, 0.37186554,
       0.96410252, 0.10243966, 0.96845447, 0.82413058, 0.53246082])

In [218]:
arr = np.random.standard_normal(size = 5)
arr

array([-1.59241765,  0.64979488,  0.63936963,  0.88614425, -1.75619032])

In [219]:
arr = np.random.uniform(size = 5)
arr

array([0.95917032, 0.30033905, 0.78608474, 0.1309677 , 0.85804019])

3.4 유니버설 함수  
반복문 없이 배열 전체에 계산을 해주는 함수

In [220]:
# 0 ~ 9 숫자가 담긴 1차원 배열 생성
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [223]:
# 파이썬의 리스트는 for문을 사용해서 계산해야함
# 넘파이의 배열은 for문 없이 계산 가능
# 배열 전체에 3 더하기
# add
np.add(arr, 3)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [225]:
a = np.array([1,7,2,4,10])
b = np.array([3,4,5,6,7])

# 두 배열을 비교하여 더 큰 값 저장
np.maximum(a, b)

array([ 3,  7,  5,  6, 10])

조건문

In [226]:
# 배열 두개 만들기
a = np.array([1,2,3])
b = np.array([10,20,30])
# 불리언 배열 만들기(조건)
cond = np.array([True, True, False])

In [229]:
# where(조건, 참일떄 값, 거짓일때 값) : 조건문 쓰기
# 조건이 참이면 a에서 값을 선택, 거짓이면 b에서 값을 선택
# where는 삼항연산자와 비슷

result = np.where(cond, a, b)
result

array([ 1,  2, 30])

In [232]:
# 1차원 배열 생성
arr = np.array([-2,-1,0,1,2])

# 양수면 'o' 음수면 'x'로 반환
# 조건이 참일때 값, 거짓일때 값
print(arr>0)
np.where(arr > 0, 'o', 'x')



[False False False  True  True]


array(['x', 'x', 'x', 'o', 'o'], dtype='<U1')

In [237]:
# 연습문제
arr = np.array([5,12,7,20,3])
print(np.where(arr>10, '100', '0'))
arr = np.array([15,8,22,6,13])
print(np.where(arr%2==0, 1, -1))
a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])
cond = np.array([True, False, True, False, True])
print(np.where(cond, a, b))

['0' '100' '0' '100' '0']
[-1  1  1  1 -1]
[10  2 30  4 50]


통계를 구할 때 자주 사용하는 함수들  
(최대 최소 합계 평균)

In [239]:
# 파이썬의 리스트 생성
lis = [1,2,3,4,5]
sum = 0
for i in lis:
    sum += i
avg = sum / len(lis)
print(sum, avg)
    

15 3.0


In [242]:
# 넘파이 배열로 합계와 평균 구하기
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.mean(arr))
# 배열에서 제일 큰 값
print(np.max(arr))
# 배열에서 제일 작은 값
print(np.min(arr))

15
3.0
5
1


In [245]:
food = np.array(['김밥','라면','떡볶이','치킨'])
kcal = np.array([250,550,400,800])

print(np.sum(kcal))
print(np.mean(kcal))
print(np.max(kcal))
print(np.min(kcal))

2000
500.0
800
250


행/열 단위로 합계 구하기

In [273]:
arr = np.arange(1,10).reshape(3,3)
print(arr)
# 배열의 합계 구하기
print(arr.sum())
# 2차원 배열에서 행 또는 열 방향으로 합 구하기
arr.cumsum(axis=0)
arr.cumsum(axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [261]:
# 누적값 구하기
# 합을 구하는 중간 과정을 보여줌|
arr = np.array([1,2,3,4,5])
arr.cumsum()

array([ 1,  3,  6, 10, 15])

In [271]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr)
# 2차원 배열의 누적값 구하기
# 기준 설정(세로방향, 위->아래)
# 앞에 있는 수를 더한 결과
print(arr.cumsum(axis=0))
# 가로방향
print(arr.cumsum(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
